apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "dx-sample-app.fullname" . }}
  labels:
    {{- include "dx-sample-app.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      deploymentconfig: {{ include "dx-sample-app.fullname" . }}
